# Generated by Django 5.1.6 on 2025-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="versusaigame",
            name="current_state",
            field=models.JSONField(default=list),
        ),
    ]
