# Generated by Django 5.1.6 on 2025-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0002_versusaigame_current_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="versusaigame",
            name="current_infostate",
            field=models.JSONField(default=list),
        ),
    ]
