# Generated by Django 5.1.6 on 2025-03-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "session",
            "0004_versusaigame_has_started_versusaigame_player_to_move_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="versusaigame",
            name="blue_anticipating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="versusaigame",
            name="red_anticipating",
            field=models.BooleanField(default=False),
        ),
    ]
