# Generated by Django 5.1.6 on 2025-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0005_versusaigame_blue_anticipating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="versusaigame",
            name="has_ended",
            field=models.BooleanField(default=False),
        ),
    ]
