# Generated by Django 5.1.6 on 2025-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0006_versusaigame_has_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="versusaigame",
            name="attack_location",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="versusaigame",
            name="previous_action",
            field=models.CharField(default="", max_length=4),
        ),
        migrations.AddField(
            model_name="versusaigame",
            name="previous_result",
            field=models.IntegerField(default=-1),
        ),
    ]
