# Generated by Django 5.1.6 on 2025-04-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0007_versusaigame_attack_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="versusaigame",
            name="winner",
            field=models.CharField(default="A", max_length=1),
        ),
    ]
